"""initial schema

Revision ID: 3a0088a88ce7
Revises:
Create Date: 2026-06-14 08:29:08.774343
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a0088a88ce7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "libraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("watch_enabled", sa.Boolean(), nullable=False),
        sa.Column("recursive", sa.Boolean(), nullable=False),
        sa.Column("patterns", sa.JSON(), nullable=True),
        sa.Column("video_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("thumb_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("poster_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fanart_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("extrafanart_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nfo_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trailer_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subtitle_template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actors", sa.JSON(), nullable=True),
        sa.Column("studio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("series", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("plot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("directors", sa.JSON(), nullable=True),
        sa.Column("poster_urls", sa.JSON(), nullable=True),
        sa.Column("thumb_urls", sa.JSON(), nullable=True),
        sa.Column("trailer_urls", sa.JSON(), nullable=True),
        sa.Column("extrafanart_urls", sa.JSON(), nullable=True),
        sa.Column("scores", sa.JSON(), nullable=True),
        sa.Column("external_ids", sa.JSON(), nullable=True),
        sa.Column("source_urls", sa.JSON(), nullable=True),
        sa.Column("field_sources", sa.JSON(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metadata_number"), "metadata", ["number"], unique=True)
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resources_url"), "resources", ["url"], unique=True)
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cron", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_type", sa.Enum("CLEANUP", "UPSCALE", name="routinetype"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("SCRAPE", "ORGANIZE", "REFRESH", "CLEANUP", "UPSCALE", name="tasktype"), nullable=False
        ),
        sa.Column("status", sa.Enum("QUEUED", "RUNNING", "DONE", "FAILED", name="taskstatus"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("log_file", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_type"), "tasks", ["type"], unique=False)
    op.create_table(
        "media_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("oshash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("codec", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "SCRAPED", "FAILED", "SKIP", name="mediafilestatus"), nullable=False),
        sa.Column("metadata_id", sa.Integer(), nullable=True),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["metadata_id"],
            ["metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_files_library_id"), "media_files", ["library_id"], unique=False)
    op.create_index(op.f("ix_media_files_metadata_id"), "media_files", ["metadata_id"], unique=False)
    op.create_index(op.f("ix_media_files_number"), "media_files", ["number"], unique=False)
    op.create_index(op.f("ix_media_files_path"), "media_files", ["path"], unique=True)
    op.create_index(op.f("ix_media_files_status"), "media_files", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_files_status"), table_name="media_files")
    op.drop_index(op.f("ix_media_files_path"), table_name="media_files")
    op.drop_index(op.f("ix_media_files_number"), table_name="media_files")
    op.drop_index(op.f("ix_media_files_metadata_id"), table_name="media_files")
    op.drop_index(op.f("ix_media_files_library_id"), table_name="media_files")
    op.drop_table("media_files")
    op.drop_index(op.f("ix_tasks_type"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_resources_url"), table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_metadata_number"), table_name="metadata")
    op.drop_table("metadata")
    op.drop_table("libraries")
    # ### end Alembic commands ###
