"""task links and root_task_id

Revision ID: 6d548c449081
Revises: bb251537757f
Create Date: 2026-08-21 13:47:27.743562
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d548c449081"
down_revision: str | None = "bb251537757f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_task_id", sa.Integer(), nullable=False),
        sa.Column("child_task_id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_task_id", "key", name="uq_task_links_parent_key"),
    )
    op.create_index(op.f("ix_task_links_child_task_id"), "task_links", ["child_task_id"], unique=False)
    op.create_index(op.f("ix_task_links_parent_task_id"), "task_links", ["parent_task_id"], unique=False)
    op.add_column("tasks", sa.Column("root_task_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_tasks_root_task_id"), "tasks", ["root_task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_root_task_id"), table_name="tasks")
    op.drop_column("tasks", "root_task_id")
    op.drop_index(op.f("ix_task_links_parent_task_id"), table_name="task_links")
    op.drop_index(op.f("ix_task_links_child_task_id"), table_name="task_links")
    op.drop_table("task_links")
    # ### end Alembic commands ###
