"""feeds and feed items

Revision ID: e6bb72730558
Revises: 4a030237ec13
Create Date: 2026-08-16 21:26:21.490443
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6bb72730558"
down_revision: str | None = "4a030237ec13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("number_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("use_cache", sa.JSON(), nullable=False),
        sa.Column("etag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_modified", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("next_fetch_at", sa.DateTime(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_enqueued", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feeds_url"), "feeds", ["url"], unique=True)
    op.create_table(
        "feed_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("item_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_id", "item_key", name="uq_feed_items_feed_id_item_key"),
    )
    op.create_index(op.f("ix_feed_items_feed_id"), "feed_items", ["feed_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feed_items_feed_id"), table_name="feed_items")
    op.drop_table("feed_items")
    op.drop_index(op.f("ix_feeds_url"), table_name="feeds")
    op.drop_table("feeds")
    # ### end Alembic commands ###
