<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <AssemblyName>Amane</AssemblyName>
    <RootNamespace>Amane</RootNamespace>
    <Product>Amane</Product>
    <Version Condition="'$(Version)' == ''">0.0.0</Version>
    <ApplicationTitle>Amane</ApplicationTitle>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../assets/app.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
